# Generated by Django 4.0.4 on 2022-05-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('DNI', models.IntegerField(max_length=8)),
                ('nacimiento', models.CharField(max_length=10)),
            ],
        ),
    ]
